---
- name: Check for presence of web and task deployments
  k8s_info:
    api_version: v1
    kind: Deployment
    name: "{{ item }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  loop: 
     - "{{ ansible_operator_meta.namespace }}-web"
     - "{{ ansible_operator_meta.namespace }}-task"
  register: tower_deployment

# Just execute deployment steps when auto_upgrade is true or when no deployment exists
- name: Start installation
  include_tasks: install.yml
  when: (tower_deployment['resources'] | length > 0 and auto_upgrade | bool ) or (tower_deployment['resources'] | length == 0)
